NIVELES_AREAS_INTERNAS = [ 1, 2, 3 ]
NIVELES_AREAS_EXTERNAS = [ 4, 5 ]
NIVELES_AREAS_TERRITORIOS = [ 6, 7 ]
DIRECCION_ADMINISTRACION_ID = 2
DEPARTAMENTO_ADMINISTRACION_ID = 46
DEPARTAMENTO_PROVISION_ID = 47
AREAS_AR_IDS = [ 2, 46, 47 ]
